name: color_print
description: This package will allow you to focus on important prints in the terminal
version: 1.0.3
homepage: https://github.com/FlagElitov/color_print

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
